"""add user avatar url

Revision ID: 145c974ddaf
Revises: 20e76fbc8f6
Create Date: 2014-08-14 19:45:10.758165
"""

# revision identifiers, used by Alembic.
revision = '145c974ddaf'
down_revision = '20e76fbc8f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('se_user', sa.Column('avatar_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('se_user', 'avatar_url')
    ### end Alembic commands ###
